# We need to get the rmf demos but sadly they can't be installed normally because of some
# bug in fastapi that is in the current jammy
# So we just copy it from the rmf_demos image
FROM ghcr.io/ba23-robotic-fleet-management/rmf:main AS rmf_demos
# Now comes the actual build
FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DOMAIN_ID=1

RUN apt-get update && apt-get upgrade -y
# Install ROS2
RUN apt-get update && apt-get install software-properties-common -y && \
    add-apt-repository universe && \
    apt-get install curl -y && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    apt-get update && \
    apt-get install -y ros-humble-ros-base ros-dev-tools
# Install rmf_demos
COPY --from=rmf_demos /rmf_demos_ws /rmf_demos_ws
# Install deps  for colcon build
RUN apt-get update && apt-get install -y ament-cmake libyaml-cpp-dev libceres-dev libeigen3-dev python3-shapely python3-requests \
    python3-yaml python3-pyproj python3-fiona python3-rtree libproj-dev ignition-tools \
    libccd-dev liboctomap-dev libboost-filesystem-dev python3-socketio python3-fastapi \
    cyclonedds-dev ros-humble-nav2-*
# Install deps for envsubs
RUN apt-get update && apt install -y gettext-base

COPY docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["bash", "/docker-entrypoint.sh"]
